export const ACTION_ADD = 'ACTION_ADD';
export const ACTION_REMOVE = 'ACTION_REMOVE';
export const ACTION_UPDATE = 'ACTION_UPDATE';
export const ACTION_REPLACE = 'ACTION_REPLACE';
export const ACTION_CLEAR = 'ACTION_CLEAR';


